name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm install
        working-directory: website

      - run: |
          git config --global user.name  "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          echo "machine github.com login ${{ secrets.USERNAME }} password ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
          npm run publish-gh-pages
        working-directory: website
        env:
          GIT_USER: ${{ secrets.USERNAME }}
          CURRENT_BRANCH: master

  
  